"""UiState repository helpers for the Orchestrator UI."""

from __future__ import annotations

from .repository_catalog import (
    _CATALOG_GROUPS,
    _catalog_group_matches_provider,
    _catalog_group_models,
    _model_aliases,
    _models_are_aliases,
    _provider_preset_for_settings,
    _provider_settings_for_section,
    catalog_models_for_section,
    default_runtime_settings,
    provider_preset_options,
    refresh_provider_runtime_labels,
    resolve_catalog_model_for_section,
)
from .repository_fields import (
    _set_entry_text,
    _with_suspended_events,
    _write_ui_fields,
    current_ui_state,
    read_fields,
    restore_ui_state,
    save_ui_state,
    set_entry_path,
)
from .repository_runtime import (
    _ensure_catalog_model_allowed,
    _read_embedding_runtime_settings,
    _read_llm_runtime_settings,
    _read_optimizer_ocr_runtime_settings,
    _read_positive_int,
    _read_provider_settings,
    _read_required_text,
    _set_provider_entry,
    _set_runtime_entry,
    _write_runtime_settings,
    current_runtime_settings,
    restore_runtime_settings,
    save_runtime_settings,
)

__all__ = [
    "_CATALOG_GROUPS",
    "_catalog_group_matches_provider",
    "_catalog_group_models",
    "_ensure_catalog_model_allowed",
    "_model_aliases",
    "_models_are_aliases",
    "_provider_preset_for_settings",
    "_provider_settings_for_section",
    "_read_embedding_runtime_settings",
    "_read_llm_runtime_settings",
    "_read_optimizer_ocr_runtime_settings",
    "_read_positive_int",
    "_read_provider_settings",
    "_read_required_text",
    "_set_entry_text",
    "_set_provider_entry",
    "_set_runtime_entry",
    "_with_suspended_events",
    "_write_runtime_settings",
    "_write_ui_fields",
    "catalog_models_for_section",
    "current_runtime_settings",
    "current_ui_state",
    "default_runtime_settings",
    "provider_preset_options",
    "read_fields",
    "refresh_provider_runtime_labels",
    "resolve_catalog_model_for_section",
    "restore_runtime_settings",
    "restore_ui_state",
    "save_runtime_settings",
    "save_ui_state",
    "set_entry_path",
]
