from __future__ import annotations

EXPECTED_ENUM_VALUES = {
    "DatabaseEmptiness": ("empty", "filled", "unknown"),
    "SemanticReleaseState": (
        "no_semantic_release",
        "semantic_release_incomplete",
        "semantic_release_complete_not_active",
        "semantic_release_active",
        "unknown",
    ),
    "AttachPointerOwner": ("kernel_held", "pipeline_held"),
    "LockType": (
        "active_run",
        "workspace",
        "database",
        "release_attach_activation",
        "merge",
        "rebuild_overwrite",
    ),
    "LockStatus": ("active", "released", "failed", "pending_resume", "expired"),
    "UserDecision": ("confirmed", "rejected", "cancelled", "expired"),
    "InteractionKind": ("input", "selection", "confirmation", "notice", "recovery"),
    "DialogType": (
        "folder_picker",
        "folder_create_picker",
        "text_input",
        "database_path_picker",
        "active_database_choice",
        "database_list_picker",
        "input_presence_confirmation",
        "update_mode_choice",
        "generic_confirmation",
        "blocker_notice",
        "progress_notice",
        "recovery_dialog",
        "support_bundle_notice",
    ),
    "RecoveryDialogType": (
        "path_reselection_dialog",
        "missing_input_dialog",
        "overwrite_decision_dialog",
        "merge_reconciliation_dialog",
        "stale_lock_dialog",
        "rebind_database_artifact_tree_dialog",
        "discard_or_archive_staged_work_dialog",
        "partial_pipeline_run_recovery_dialog",
        "support_bundle_dialog",
    ),
    "InteractionResponseStatus": (
        "submitted",
        "cancelled",
        "closed",
        "expired",
        "superseded",
        "rejected_stale",
    ),
    "ClientFrontendEventKind": (
        "interaction_request",
        "progress_event",
        "mirror_event",
        "tool_availability",
        "interaction_resolved",
    ),
    "RiskClass": ("read_only", "non_destructive", "long_running", "destructive", "support"),
    "ProgressStatus": (
        "step_started",
        "step_completed",
        "waiting_for_user",
        "blocked",
        "retrying",
        "cancelled",
        "completed",
        "failed",
    ),
    "ProgressEventType": ("workflow_step", "pipeline_step", "llm_step", "user_interaction", "recovery_step"),
    "MirrorSource": ("kernel",),
    "MirrorEventType": (
        "progress",
        "input_dialog_opened",
        "selection_dialog_opened",
        "confirmation_dialog_opened",
        "blocker",
        "recovery_state",
        "validation_error",
        "pipeline_error",
        "llm_validation_retry",
        "llm_validation_failed_final",
        "workflow_completed",
        "workflow_cancelled",
    ),
    "MirrorSeverity": ("info", "warning", "recoverable_error", "final_error"),
    "RecoveryOwner": ("kernel_dialog", "agent_tool", "user_filesystem_action", "kernel_internal", "support_surface"),
    "RecoveryActionType": (
        "reopen_dialog",
        "apply_kernel_option",
        "retry_same_workflow",
        "inspect_resume_state",
        "cancel_active_workflow",
        "start_new_workflow",
        "discard_or_archive_staged_work",
        "open_support_bundle",
        "support_only",
        "user_filesystem_fix",
    ),
    "RecoveryStateClass": (
        "stale_lock",
        "target_identity_changed",
        "broken_database_artifact_binding",
        "semantic_release_incomplete_staged",
        "partial_pipeline_run",
        "unresolved_merge_collision",
        "missing_manifest_or_originals",
        "final_llm_validation_failure",
        "expired_pending_interaction",
        "support_only_unrecoverable",
    ),
    "RecoveryResultStatus": ("applied", "rejected", "stale", "cancelled", "support_only", "failed"),
    "AnalysisScope": ("sample_set",),
    "TaxonomySource": ("active", "staged", "custom_taxonomy_update_state"),
    "TaxonomyViewMode": ("complete", "relevant_slice"),
    "DatabaseCoverageQuality": ("good", "mixed", "weak"),
    "SampleStructureShape": ("text", "form", "table", "form_with_table", "list", "mixed"),
    "ValueType": ("string", "date_or_string", "number_or_string", "number_or_money_string"),
    "ProposalStatus": ("draft", "active", "deprecated"),
    "LLMParseStatus": ("valid_json", "invalid_json", "missing_output", "not_json_object", "not_json_array"),
    "LLMValidationStatus": ("passed", "failed", "not_run"),
    "LLMResponseStatus": ("complete", "incomplete", "error"),
    "LLMValidationFailureCode": (
        "invalid_json",
        "markdown_outside_json",
        "schema_version_mismatch",
        "missing_required_fields",
        "unknown_fields",
        "enum_mismatch",
        "source_fingerprint_mismatch",
        "taxonomy_fingerprint_mismatch",
        "projection_fingerprint_mismatch",
        "sample_id_mismatch",
        "database_reference_mismatch",
        "unknown_taxonomy_code",
        "unknown_projection_id",
        "invalid_update_state_family",
        "invalid_promotion_path",
        "function_rule_violation",
    ),
    "TaxonomySampleHintType": ("possible_match", "possible_gap", "possible_misfit"),
    "TaxonomyDatabaseGapSource": ("taxonomy_gap_seed", "issue_cluster", "coverage_metric", "affected_document"),
    "TaxonomyDatabaseHintType": ("possible_gap", "possible_extension"),
    "ProjectionSampleHintType": ("possible_match", "possible_gap", "possible_misfit"),
    "ProjectionDatabaseGapSource": (
        "projection_gap_seed",
        "issue_cluster",
        "coverage_metric",
        "slot_coverage",
        "affected_document",
    ),
    "ProjectionDatabaseHintType": (
        "possible_projection_extension",
        "possible_new_projection",
        "possible_promotion_rule",
    ),
    "MergeRoute": ("empty_databases_merge_path", "filled_databases_merge_path"),
    "MergeCollisionResolutionStatus": ("unresolved", "resolved", "requires_user_choice", "support_only"),
    "PipelineBatchKind": (
        "manual_ingest",
        "sample_ingest",
        "reingest_all_originals",
        "reingest_selected_samples",
        "workflow_continuation_ingest",
    ),
    "PipelineBatchStatus": ("finalized",),
}
