from __future__ import annotations

from phase12_merge_entry_fixtures import create_artifact_tree, seed_rebuild_release, source, target_root
from phase12_merge_entry_embedding_adapter import FakeEmbeddingAdapter
from phase12_merge_entry_results import ok_result, owner_error
from phase12_merge_entry_runtime import runtime_for
from phase12_merge_entry_semantic_adapter import FakeSemanticReleaseAdapter
from phase12_merge_entry_workspace_corpus import FakeCorpusAdapter
