from __future__ import annotations


MIRROR_EVENT_HARD_CAP = 20
WORKFLOW_HISTORY_HARD_CAP = 20
PROGRESS_WORKFLOW_DIR_HARD_CAP = 20
PROGRESS_FILES_PER_WORKFLOW_HARD_CAP = 200
PENDING_CONFIRMATION_HISTORY_HARD_CAP = 50
PENDING_INTERACTION_HISTORY_HARD_CAP = 50
LOCK_HISTORY_HARD_CAP = 50
RECEIPT_OPERATION_HARD_CAP = 200
RECEIPT_CONFIRMATION_HARD_CAP = 100
RECEIPT_RECOVERY_HARD_CAP = 100
NESTED_HISTORY_DIR_HARD_CAP = 20
NESTED_HISTORY_FILES_PER_DIR_HARD_CAP = 10
TRACE_WORKFLOW_DIR_HARD_CAP = 20
DEBUG_ADAPTER_WORKFLOW_DIR_HARD_CAP = 20
DEBUG_ADAPTER_FILES_PER_WORKFLOW_HARD_CAP = 100
DEBUG_LLM_RUN_DIR_HARD_CAP = 20
DEBUG_LLM_FILES_PER_RUN_HARD_CAP = 20
RAW_ADAPTER_CALL_DIR_HARD_CAP = 50
RAW_ADAPTER_CALL_TOTAL_BYTES_HARD_CAP = 256 * 1024 * 1024
RAW_ADAPTER_CALL_DIR_BYTES_HARD_CAP = 32 * 1024 * 1024
RAW_ADAPTER_CALL_STRUCTURED_FILE_BYTES_HARD_CAP = 8 * 1024 * 1024
RAW_ADAPTER_CALL_RAW_RESPONSE_FILE_BYTES_HARD_CAP = 16 * 1024 * 1024
RAW_ADAPTER_CALL_TEXT_FILE_BYTES_HARD_CAP = 1024 * 1024
FS_LOCK_FILE_HARD_CAP = 512
TMP_FILE_HARD_CAP = 50
TMP_FILE_MIN_AGE_SECONDS = 60
SUPPORT_BUNDLE_HARD_CAP = 20
SUPPORT_CLEANUP_HISTORY_HARD_CAP = 20
ARCHIVE_RESET_HARD_CAP = 20
QUARANTINE_ENTRY_HARD_CAP = 20
