"""Ontology read-surface column contracts."""

from __future__ import annotations

ONTOLOGY_READ_SURFACE_COLUMNS = {
    "vw_active_ontology_nodes": (
        "ontology_id",
        "ontology_name",
        "node_id",
        "node_type",
        "canonical_label",
        "source_ref_type",
        "source_ref_id",
        "summary",
        "attributes_json",
        "confidence",
        "status",
        "embedding_status",
    ),
    "vw_active_ontology_edges": (
        "ontology_id",
        "ontology_name",
        "edge_id",
        "source_node_id",
        "source_label",
        "target_node_id",
        "target_label",
        "relation_type",
        "relation_label",
        "attributes_json",
        "confidence",
        "status",
        "evidence_count",
    ),
    "vw_active_ontology_assertions": (
        "ontology_id",
        "ontology_name",
        "assertion_id",
        "subject_ref_type",
        "subject_ref_id",
        "predicate",
        "object_ref_type",
        "object_ref_id",
        "value_text",
        "confidence",
        "status",
        "evidence_count",
    ),
    "vw_query_surface_with_active_ontology": (
        "surface_type",
        "surface_id",
        "ontology_id",
        "source_document_id",
        "document_id",
        "label",
        "body_text",
        "source_ref_type",
        "source_ref_id",
        "status",
        "confidence",
        "embedding_status",
        "metadata_json",
    ),
}
