from __future__ import annotations

from typing import Any

PLAYBOOKS: tuple[dict[str, Any], ...] = (
    {
        "playbook_id": "what_can_i_do",
        "title": "Was kann ich mit der Datenbank tun?",
        "goal_de": "Der User will Orientierung statt sofortiger Ausfuehrung.",
        "recommended_first_kernel_tool": "kernel_status",
        "recommended_first_mcp_tool": None,
        "recommended_first_step_de": "Zuerst aktuellen DB-, Workspace- und Input-Zustand lesen.",
        "why_de": "Danach kann der Agent zwischen Suchen, Importieren, Regeln verbessern, Export, Reparatur oder Neuaufbau unterscheiden.",
        "safe_next_kernel_tools": ["kernel_status", "empty_database_default_taxonomy_default_projections", "empty_database_default_taxonomy_no_projections", "create_custom_taxonomy_path", "manual_pipeline_run"],
        "safe_next_mcp_tools": ["inspect_current_environment_status", "search_corpus", "corpus_stats"],
        "keywords": ("was kann", "tun", "moeglich", "moeglichkeiten", "wozu", "gut", "ueberblick", "orientierung"),
    },
    {
        "playbook_id": "new_document_kind",
        "title": "Neue Dokumentart sauber aufnehmen",
        "goal_de": "Neue Dateien sollen die aktive Datenbank besser abbilden lassen.",
        "recommended_first_kernel_tool": "create_custom_taxonomy_path",
        "recommended_first_mcp_tool": None,
        "recommended_first_step_de": "Die unterstuetzten Dateien im aktiven Input-Ordner gemeinsam als Sample-Set pruefen.",
        "why_de": "Eine Datenbank besteht normalerweise aus heterogenen Dokumenten; Sample-Sets reduzieren Single-Document-Overfitting.",
        "safe_next_kernel_tools": ["create_custom_taxonomy_path", "create_custom_projection_path", "manual_pipeline_run"],
        "safe_next_mcp_tools": ["review_source_sample_set_taxonomy_coverage"],
        "keywords": ("neue dokumentart", "neuer dokumenttyp", "sample", "mehrere dokumente", "input ordner", "diese art dokumente", "besser abbilden"),
    },
    {
        "playbook_id": "taxonomy_change",
        "title": "Feldsammlung erweitern",
        "goal_de": "Neue Inhalte sollen als echte Archivfelder verfuegbar werden.",
        "recommended_first_kernel_tool": "create_custom_taxonomy_path",
        "recommended_first_mcp_tool": None,
        "recommended_first_step_de": "Aus dem Coverage-Befund eine Arbeitsfassung der Regelversion entwerfen und pruefen.",
        "why_de": "Feldlogik, Profilzuordnung und Aktivierung muessen zusammenpassen; reine Klassifikation reicht dafuer nicht.",
        "safe_next_kernel_tools": ["create_custom_taxonomy_path", "create_custom_projection_path", "empty_database_default_taxonomy_no_projections"],
        "safe_next_mcp_tools": ["review_source_document_taxonomy_coverage"],
        "keywords": ("taxonomie", "felder", "field", "coverage", "erweitern", "regeln schaerfen"),
    },
    {
        "playbook_id": "reimport_after_change",
        "title": "Nach grossen Regelwechseln neu einlesen",
        "goal_de": "Alte und neue Dokumente sollen mit der neuen Feldlogik verarbeitet werden.",
        "recommended_first_kernel_tool": "database_rebuild_from_artifacts",
        "recommended_first_mcp_tool": None,
        "recommended_first_step_de": "Nur die zur aktiven DB gehoerenden alten Originale anhand gespeicherter Hashes zurueck in den Input vorbereiten.",
        "why_de": "So werden andere Dateien im Originals-Ordner nicht versehentlich verarbeitet und es entstehen keine doppelten Originalkopien.",
        "safe_next_kernel_tools": [
            "database_rebuild_from_artifacts",
            "reset_database",
            "manual_pipeline_run",
        ],
        "safe_next_mcp_tools": [],
        "keywords": ("reimport", "neu einlesen", "alte dokumente", "originale", "input", "neue db", "reset"),
    },
    {
        "playbook_id": "why_architecture",
        "title": "Warum ist das so getrennt?",
        "goal_de": "Der User will die Architekturentscheidung verstehen.",
        "recommended_first_kernel_tool": "kernel_status",
        "recommended_first_mcp_tool": "inspect_pipeline_contract_governance",
        "recommended_first_step_de": "Produkt-Semantik erklaeren: Datenbank, Workspace, Regeln, Projections, Originals und Reimport trennen Verantwortlichkeiten.",
        "why_de": "Die Trennung verhindert stille Strukturwechsel, ermoeglicht reproduzierbaren Neuaufbau und schuetzt bestehende Archive.",
        "safe_next_kernel_tools": ["kernel_status"],
        "safe_next_mcp_tools": ["inspect_pipeline_contract_governance", "inspect_pipeline_product_context"],
        "keywords": ("warum", "weshalb", "so und nicht anders", "architektur", "wozu", "sinn"),
    },
    {
        "playbook_id": "search_not_good",
        "title": "Suche findet nicht das Erwartete",
        "goal_de": "Der User will verstehen, ob Inhalte fehlen, Suchdaten fehlen oder Regeln zu grob waren.",
        "recommended_first_kernel_tool": None,
        "recommended_first_mcp_tool": "search_corpus",
        "recommended_first_step_de": "Zuerst Statistik/Suche pruefen, danach entscheiden: Embeddings erzeugen, Regeln schaerfen oder Reimport planen.",
        "why_de": "Schlechte Suchtreffer koennen von leerem Input, fehlenden Embeddings, zu groben Feldern oder falscher Profilzuordnung kommen.",
        "safe_next_kernel_tools": ["create_custom_taxonomy_path", "create_custom_projection_path", "database_rebuild_from_artifacts"],
        "safe_next_mcp_tools": ["search_corpus", "corpus_stats", "export_corpus"],
        "keywords": ("suche", "findet nicht", "nicht gefunden", "search", "treffer", "inhalt"),
    },
)

__all__ = ["PLAYBOOKS"]
