from __future__ import annotations

from typing import Any

CARDS: tuple[dict[str, Any], ...] = (
    {
        "concept_id": "database",
        "title": "Datenbank",
        "plain_meaning_de": "Die Datei, in der verarbeitete Dokumente, Suchdaten und der aktive Regelstand liegen.",
        "why_it_exists_de": "So bleibt ein Archiv dauerhaft such- und pruefbar gespeichert.",
        "typical_actions_de": ["Status pruefen", "Inhalte suchen", "Statistik ansehen", "exportieren", "neu aufbauen"],
        "related_kernel_tool_names": ["kernel_status", "create_custom_taxonomy_path", "database_rebuild_from_artifacts"],
        "related_mcp_tool_names": ["search_corpus", "corpus_stats", "export_corpus"],
        "keywords": ("datenbank", "db", "archive", "archiv", "corpus", "sammlung"),
    },
    {
        "concept_id": "workspace",
        "title": "Workspace und Artefaktbaum",
        "plain_meaning_de": "Der Arbeitsordner einer Sammlung: Input, Corpus, Originale, Logs und Hilfsdateien.",
        "why_it_exists_de": "Rohe Dateien, Ergebnisse und DB-Zustand bleiben fuer Neuaufbau und Diagnose getrennt.",
        "typical_actions_de": ["aktive Pfade pruefen", "Input vorbereiten", "Originale fuer Reimport verwenden"],
        "related_kernel_tool_names": ["kernel_status", "empty_database_default_taxonomy_default_projections", "database_rebuild_from_artifacts"],
        "related_mcp_tool_names": ["inspect_current_environment_status"],
        "keywords": ("workspace", "arbeitsordner", "artifact", "artefakt", "pfad", "folder", "ordner"),
    },
    {
        "concept_id": "input_folder",
        "title": "Input-Ordner",
        "plain_meaning_de": "Der Eingang fuer Dateien, die beim naechsten Pipeline-Lauf verarbeitet werden sollen.",
        "why_it_exists_de": "Neue Verarbeitung ist explizit: Was im Input liegt, ist die aktuelle Warteschlange.",
        "typical_actions_de": ["neue Dateien vorbereiten", "Pipeline-Lauf starten", "Input-Leerstand erklaeren"],
        "related_kernel_tool_names": ["manual_pipeline_run", "create_custom_taxonomy_path", "create_custom_projection_path"],
        "related_mcp_tool_names": ["inspect_current_environment_status"],
        "keywords": ("input", "eingabe", "eingang", "neue dateien", "verarbeiten"),
    },
    {
        "concept_id": "originals_folder",
        "title": "Originale",
        "plain_meaning_de": "Die abgelegten Quelldateien bereits importierter Dokumente.",
        "why_it_exists_de": "Alte Dokumente koennen nach einer Regelverbesserung ohne manuelles Sortieren neu eingelesen werden.",
        "typical_actions_de": ["alte DB-Originale auswaehlen", "Reimport vorbereiten", "andere Dateien unangetastet lassen"],
        "related_kernel_tool_names": [
            "database_rebuild_from_artifacts",
            "reset_database",
            "manual_pipeline_run",
        ],
        "related_mcp_tool_names": [],
        "keywords": ("original", "originale", "originals", "quelldokument", "alte dokumente", "reimport"),
    },
    {
        "concept_id": "semantic_release",
        "title": "Erkennungsregeln",
        "plain_meaning_de": "Eine gespeicherte Version der Regeln: Dokumentarten, Felder und Importhinweise.",
        "why_it_exists_de": "Die Datenbank weiss dadurch, mit welcher Feldlogik sie erzeugt wurde.",
        "typical_actions_de": ["aktive Version lesen", "Regeln entwerfen", "validieren", "exportieren", "aktivieren"],
        "related_kernel_tool_names": ["kernel_status", "create_custom_taxonomy_path", "create_custom_projection_path"],
        "related_mcp_tool_names": ["read_active_semantic_release"],
        "keywords": ("release", "regeln", "erkennungsregeln", "regelversion", "extraktionsregeln"),
    },
    {
        "concept_id": "taxonomy_change",
        "title": "Feldsammlung erweitern",
        "plain_meaning_de": "Neue feste Archivfelder oder neue Dokumentarten aufnehmen.",
        "why_it_exists_de": "Wiederkehrende neue Inhalte brauchen eine semantische Erweiterung der Regelversion.",
        "typical_actions_de": ["Sample-Set pruefen", "Feldvorschlag entwerfen", "Kompatibilitaet pruefen", "neu einlesen"],
        "related_kernel_tool_names": ["create_custom_taxonomy_path", "create_custom_projection_path", "manual_pipeline_run"],
        "related_mcp_tool_names": ["inspect_current_environment_status"],
        "keywords": ("taxonomie", "feld", "felder", "coverage", "abdeckung", "luecke", "uebersehen", "erweitern"),
    },
    {
        "concept_id": "projection_routing",
        "title": "Dokumentprofil und Zuordnung",
        "plain_meaning_de": "Hinweise, welches Regelprofil fuer eine Datei passt und welche Felder darin aktiv sind.",
        "why_it_exists_de": "Manchmal fehlen keine Felder; die Zuordnung zum richtigen Profil ist nur zu eng.",
        "typical_actions_de": ["Routing-Hinweise schaerfen", "Profil pruefen", "Aktivierung vorab testen"],
        "related_kernel_tool_names": ["create_custom_projection_path"],
        "related_mcp_tool_names": ["inspect_current_environment_status"],
        "keywords": ("profil", "projection", "projektion", "routing", "zuordnung", "klassifikation"),
    },
    {
        "concept_id": "backfill_vs_reimport",
        "title": "Backfill oder Reimport",
        "plain_meaning_de": "Backfill frischt Ableitungen auf; Reimport liest Quelldateien mit neuen Regeln neu.",
        "why_it_exists_de": "Neue Felder koennen aus alten Normalisaten nicht verlaesslich entstehen.",
        "typical_actions_de": ["Kompatibilitaet klassifizieren", "bei gleicher Struktur backfillen", "bei Taxonomie-Aenderung neu einlesen"],
        "related_kernel_tool_names": [
            "database_rebuild_from_artifacts",
            "manual_pipeline_run",
        ],
        "related_mcp_tool_names": ["semantic_audit"],
        "keywords": ("backfill", "reimport", "neu einlesen", "neuaufbau", "inkompatibel", "alte dateien"),
    },
    {
        "concept_id": "sample_set_refinement",
        "title": "Regeln aus mehreren Beispielen schaerfen",
        "plain_meaning_de": "Die unterstuetzten Dateien im aktiven Input-Ordner gemeinsam auswerten, damit Regeln auf die Dokumentgruppe passen.",
        "why_it_exists_de": "Das verhindert Ueberanpassung an ein einzelnes Dokument.",
        "typical_actions_de": ["Samples gemeinsam pruefen", "wiederkehrende Felder bestimmen", "Einzelfaelle optional behandeln"],
        "related_kernel_tool_names": ["create_custom_taxonomy_path", "create_custom_projection_path"],
        "related_mcp_tool_names": ["review_source_sample_set_taxonomy_coverage"],
        "keywords": ("sample", "samples", "beispiele", "mehrere dokumente", "diese art dokumente", "heterogen"),
    },
    {
        "concept_id": "search_quality",
        "title": "Suche und Auswertung",
        "plain_meaning_de": "Die Datenbank kann durchsucht, zusammengefasst und exportiert werden.",
        "why_it_exists_de": "Das Archiv ist nicht nur Ablage, sondern eine strukturierte Such- und Analysebasis.",
        "typical_actions_de": ["Statistik lesen", "Volltext suchen", "Embeddings erzeugen", "Export erstellen"],
        "related_kernel_tool_names": ["kernel_status"],
        "related_mcp_tool_names": ["search_corpus", "corpus_stats", "export_corpus"],
        "keywords": ("suche", "finden", "was steht", "inhalt", "export", "statistik", "embedding"),
    },
    {
        "concept_id": "repair_rebuild",
        "title": "Reparatur und Neuaufbau",
        "plain_meaning_de": "Diagnose- und Wiederaufbaupfade fuer unvollstaendige oder inkonsistente Artefakte.",
        "why_it_exists_de": "Fehler werden ueber nachvollziehbare Workflow-Schritte geloest, nicht durch Handarbeit im Dateibaum.",
        "typical_actions_de": ["Zustand pruefen", "Artefakte neu aufbauen", "Supportfall erzeugen"],
        "related_kernel_tool_names": ["database_rebuild_from_artifacts", "kernel_status"],
        "related_mcp_tool_names": ["assess_support_incident", "inspect_pipeline_contract_governance"],
        "keywords": ("reparieren", "repair", "kaputt", "fehler", "neu aufbauen", "wiederherstellen"),
    },
)

__all__ = ["CARDS"]
