"""Bootstrap planning shared by review and apply actions."""
from __future__ import annotations

from copy import deepcopy
from typing import Any

from .draft_ids import build_lookup, derive_projection_id, derive_term_id, existing_term
from .draft_package import ensure_master_term, ensure_projection_clone, ensure_projection_include, master_templates, merge_routing_markers, section_for_phrase, update_projection_text
from .impact_preview import describe_package_delta
from . import locale_views
from .review_support import compact_ranking, excerpt_text, load_review_context, select_review_projection, split_statements


def build_bootstrap_plan(project_root, payload: dict[str, Any]) -> dict[str, object]:
    goal = _required_text(payload.get("goal"), label="goal")
    must_keep = _required_text(payload.get("must_keep"), label="must_keep")
    noise_tolerance = _noise_tolerance(payload.get("noise_tolerance"))
    context = load_review_context(project_root)
    lookup = build_lookup(context["package"])
    templates = master_templates(context["package"])
    selection, ranking = select_review_projection(context, _bootstrap_doc(goal, must_keep))
    candidate = deepcopy(context["package"])
    target_projection_id = selection.profile.projection_id
    warnings = []
    applied_changes = []
    if _should_clone(ranking):
        derived = derive_projection_id(candidate, lookup, goal, target_projection_id)
        target_projection_id = derived["projection_id"]
        ensure_projection_clone(candidate, selection.profile.projection_id, target_projection_id)
        update_projection_text(
            candidate,
            target_projection_id,
            label=f"Draft projection for {excerpt_text(goal, limit=48)}",
            description="Autogenerated draft projection derived from bootstrap goals.",
            when_to_use=excerpt_text(goal, limit=160),
            avoid_when="Review domain fit and routing lexicon before release.",
        )
        applied_changes.append({"action": "clone_projection", "target": target_projection_id, "source": selection.profile.projection_id, "reason": "Bestehende Projection reagiert auf die Zielaussagen noch zu schwach."})
        if derived["requires_id_review"]:
            warnings.append(f"Neue Projection-ID '{target_projection_id}' ist nur heuristisch abgeleitet und braucht Review.")
    else:
        applied_changes.append({"action": "reuse_projection", "target": target_projection_id, "reason": selection.reason})
    markers = merge_routing_markers(candidate, target_projection_id, goal, must_keep, limit=_marker_limit(noise_tolerance))
    if markers:
        applied_changes.append({"action": "update_routing_lexicon", "target": target_projection_id, "reason": f"{len(markers)} routing markers from bootstrap input were added."})
    suggestions = []
    balance = {"kept": [], "condensed": [], "lost": []}
    for phrase in split_statements(must_keep):
        current = existing_term(candidate, lookup, phrase)
        if current is not None:
            section_id, term_id = current
            if ensure_projection_include(candidate, target_projection_id, section_id, term_id):
                applied_changes.append({"action": "extend_projection", "target": target_projection_id, "reason": f"Bestehender Code '{term_id}' wurde in die Projection aufgenommen."})
            suggestions.append({"section_id": section_id, "term_id": term_id, "label": phrase, "suggestion_type": "reuse", "reason": f"Bestehender Begriff deckt '{phrase}' bereits ab."})
            balance["kept"].append(phrase)
            continue
        section_id = section_for_phrase(phrase)
        derived = derive_term_id(candidate, lookup, section_id, phrase)
        created = ensure_master_term(candidate, templates, section_id, derived["term_id"], target_projection_id, phrase=phrase, origin="Bootstrap")
        ensure_projection_include(candidate, target_projection_id, section_id, derived["term_id"])
        if created:
            applied_changes.append({"action": "create_master_term", "target": f"{section_id}.{derived['term_id']}", "reason": f"Neuer Draft-Begriff fuer '{phrase}' angelegt."})
        applied_changes.append({"action": "extend_projection", "target": target_projection_id, "reason": f"Neuer Draft-Code '{derived['term_id']}' wurde in die Projection aufgenommen."})
        suggestions.append({"section_id": section_id, "term_id": derived["term_id"], "label": phrase, "suggestion_type": "new", "reason": f"Kein passender Master-Begriff vorhanden; Draft fuer '{phrase}' angelegt."})
        balance["lost"].append(phrase)
        if derived["requires_id_review"]:
            warnings.append(f"Neue Term-ID '{derived['term_id']}' fuer '{phrase}' braucht Review.")
    impact = describe_package_delta(project_root, candidate, materialization_version=context["release_preview"]["materialization_version"])
    warnings.extend(_warnings(ranking, balance["lost"]))
    review_payload = {
        "review_mode": "bootstrap",
        "language_policy": {
            "available_locales": list(candidate["release"]["available_locales"]),
            "default_authoring_locale": candidate["release"]["default_authoring_locale"],
            "document_scope": "Locale-aware source package",
        },
        "input_summary": {"goal": goal, "must_keep": must_keep, "noise_tolerance": noise_tolerance},
        "release_summary": {"release_id": context["release_preview"]["release_id"], "release_version": context["release_preview"]["release_version"], "candidate_fingerprint": impact["candidate_release_fingerprint"], "projection_count": len(candidate["release"]["projection_ids"])},
        "projection_suggestions": _projection_review(candidate, selection.profile.projection_id, target_projection_id, ranking),
        "master_term_suggestions": suggestions,
        "routing_review": {"selected_projection_id": target_projection_id, "selected_reason": selection.reason, "candidate_rankings": compact_ranking(ranking), "warnings": warnings},
        "document_comparison": {"original": {"status": "not_available", "summary": "Bootstrap-Modus ohne Quelldokument."}, "structured": {"status": "not_available", "summary": "Kein structured Sample im Bootstrap-Review."}, "normalized": {"status": "not_available", "summary": "Normalisierungsvergleich folgt erst im Data-Informed-Review."}},
        "information_balance": balance,
        "warnings": warnings,
        "next_steps": _next_steps(applied_changes, warnings),
    }
    return {"candidate_package": candidate, "review_payload": review_payload, "applied_changes": applied_changes, "impact": impact, "references": list(candidate["release"]["projection_ids"])}


def _bootstrap_doc(goal: str, must_keep: str) -> dict[str, object]:
    return {"classification": {"document_type": "other", "category": "other", "subcategory": "other", "is_scan": False, "has_handwriting": False, "page_count": 1}, "context": {"document_title": goal, "description": must_keep}, "content": {"structure": {"type": "free_text", "columns": [], "form_fields": []}, "fields": {}, "rows": [], "free_text": f"{goal}\n{must_keep}"}}


def _projection_review(candidate: dict[str, Any], selected_projection_id: str, target_projection_id: str, ranking: list[dict[str, Any]]) -> list[dict[str, object]]:
    results = []
    active_locale = locale_views.default_authoring_locale(candidate)
    if target_projection_id != selected_projection_id:
        results.append({"projection_id": target_projection_id, "label": candidate["projections"][target_projection_id]["texts"][active_locale]["label"], "recommended": True, "action": "clone_projection", "reason": f"Draft-Klon aus {selected_projection_id}."})
    for item in ranking[:3]:
        text = candidate["projections"][item["projection_id"]]["texts"][active_locale]
        results.append({"projection_id": item["projection_id"], "label": text["label"], "score": item["score"], "recommended": item["projection_id"] == selected_projection_id and target_projection_id == selected_projection_id, "action": "reuse", "reason": ", ".join(item["signals"][:4]) or "Keine klaren Signalscores."})
    return results


def _warnings(ranking: list[dict[str, Any]], lost: list[str]) -> list[str]:
    warnings = []
    if ranking and int(ranking[0]["score"]) <= 0:
        warnings.append("Routing-Lexika reagieren auf die Bootstrap-Aussagen noch zu schwach; die Projection-Wahl bleibt konservativ.")
    if len(ranking) > 1 and int(ranking[0]["score"]) == int(ranking[1]["score"]):
        warnings.append("Mehrere Projections sind gleich stark; die Routing-Begruendung bleibt vorlaeufig.")
    if lost:
        warnings.append("Ein Teil der Muss-Felder war noch nicht als Master-Begriff verankert und wurde als Draft angelegt.")
    return warnings


def _next_steps(applied_changes: list[dict[str, str]], warnings: list[str]) -> list[str]:
    steps = ["Gespeicherten Draft pruefen und die neu angelegten Begriffe oder Projections fachlich nachschaerfen."]
    if any(item["action"] == "clone_projection" for item in applied_changes):
        steps.append("Neue Draft-Projection in Taxonomy Profiles auf Coverage, Label und Routing pruefen.")
    if warnings:
        steps.append("Warnungen vor Validate/Compile fachlich abarbeiten.")
    steps.append("Danach `validate_release_package` und `compile_release_package` ausfuehren.")
    return steps


def _should_clone(ranking: list[dict[str, Any]]) -> bool:
    return not ranking or int(ranking[0]["score"]) <= 0 or not ranking[0]["signals"]


def _marker_limit(noise_tolerance: str) -> int:
    return {"low": 8, "medium": 6, "high": 4}[noise_tolerance]


def _required_text(value: Any, *, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{label} muss ein nicht-leerer String sein.")
    return value.strip()


def _noise_tolerance(value: Any) -> str:
    text = _required_text(value, label="noise_tolerance").casefold()
    if text not in {"low", "medium", "high"}:
        raise ValueError("noise_tolerance muss low, medium oder high sein.")
    return text
