"""Package mutation helpers for bootstrap and sample-driven draft authoring."""
from __future__ import annotations

from copy import deepcopy
from typing import Any

from ..taxonomy_sources import policy as source_policy
from . import locale_views
from .review_support import excerpt_text, infer_section_id, keyword_phrases, normalize_text

_INCLUDE_KEYS = {
    "document_types": "include_document_types",
    "categories": "include_categories",
    "subcategories": "include_subcategories",
    "field_codes": "include_field_codes",
    "row_types": "include_row_types",
    "cell_codes": "include_cell_codes",
}
_LABELS = {
    "document_types": "Draft document type",
    "categories": "Draft category",
    "subcategories": "Draft subcategory",
    "field_codes": "Draft field",
    "row_types": "Draft row",
    "cell_codes": "Draft cell",
}


def master_templates(package: dict[str, Any]) -> dict[str, dict[str, Any]]:
    templates = {}
    for section_id, entries in package["master"]["core"].items():
        if not isinstance(entries, dict) or not entries:
            continue
        template_id = "other" if "other" in entries else next(iter(entries))
        templates[section_id] = deepcopy(entries[template_id])
    return templates


def ensure_projection_clone(package: dict[str, Any], source_projection_id: str, target_projection_id: str) -> None:
    if target_projection_id in package["projections"]:
        return
    entry = deepcopy(package["projections"][source_projection_id])
    entry["core"]["projection_id"] = target_projection_id
    package["projections"][target_projection_id] = entry
    if target_projection_id not in package["release"]["projection_ids"]:
        package["release"]["projection_ids"].append(target_projection_id)
    package["release"]["projection_ids"] = source_policy.canonical_projection_id_list(
        package["release"]["projection_ids"],
        label="release.projection_ids",
    )
    package["projections"] = {
        projection_id: package["projections"][projection_id]
        for projection_id in package["release"]["projection_ids"]
    }


def ensure_projection_include(package: dict[str, Any], projection_id: str, section_id: str, term_id: str) -> bool:
    include_key = _INCLUDE_KEYS.get(section_id)
    if not include_key:
        return False
    values = package["projections"][projection_id]["core"][include_key]
    if term_id in values:
        return False
    values.append(term_id)
    return True


def ensure_master_term(
    package: dict[str, Any],
    templates: dict[str, dict[str, Any]],
    section_id: str,
    term_id: str,
    projection_id: str,
    *,
    phrase: str,
    origin: str,
) -> bool:
    if term_id in package["master"]["core"][section_id]:
        return False
    active_locale = locale_views.default_authoring_locale(package)
    core = deepcopy(templates[section_id])
    text = package["master"]["texts"][active_locale][section_id]
    projection = package["projections"][projection_id]["core"]
    if "status" in core:
        core["status"] = "draft"
    if "domains" in core:
        core["domains"] = list(projection["domain_ids"][:1] or ["other"])
    if "allowed_categories" in core:
        core["allowed_categories"] = list(projection["include_categories"][:1] or ["other"])
    if "allowed_subcategories" in core:
        core["allowed_subcategories"] = list(projection["include_subcategories"][:1] or ["other"])
    if "parent_category" in core:
        core["parent_category"] = str(projection["include_categories"][0] if projection["include_categories"] else "other")
    label = _label(section_id, text, phrase)
    text[term_id] = {
        "label": label,
        "description": f"Autogenerated {origin} draft term. Review before release.",
        "aliases": _aliases(phrase),
    }
    for locale in locale_views.available_locales(package):
        if locale == active_locale:
            continue
        package["master"]["texts"][locale][section_id].setdefault(term_id, deepcopy(text[term_id]))
    package["master"]["core"][section_id][term_id] = core
    return True


def update_projection_text(package: dict[str, Any], projection_id: str, *, label: str | None, description: str, when_to_use: str, avoid_when: str) -> None:
    text = package["projections"][projection_id]["texts"][locale_views.default_authoring_locale(package)]
    if label:
        text["label"] = label
    text["description"] = description
    text["routing"]["when_to_use"] = when_to_use
    text["routing"]["avoid_when"] = avoid_when


def merge_routing_markers(package: dict[str, Any], projection_id: str, *texts: str, limit: int) -> list[str]:
    lexicon = package["projections"][projection_id]["texts"][locale_views.default_authoring_locale(package)]["routing_lexicon"]
    additions = [marker for marker in _markers(*texts) if marker not in lexicon["text_markers"]][:limit]
    if additions:
        lexicon["text_markers"].extend(additions)
        primary_domain = next(iter(lexicon["domain_markers"]), "")
        if primary_domain:
            lexicon["domain_markers"][primary_domain] = _merge_unique(lexicon["domain_markers"][primary_domain], additions[:3])
    return additions


def section_for_phrase(phrase: str) -> str:
    raw = str(phrase or "").strip()
    if "_" in raw:
        return "field_codes"
    return infer_section_id(raw)


def _label(section_id: str, text_entries: dict[str, Any], phrase: str) -> str:
    normalized = normalize_text(phrase)
    if " " in phrase and not normalized.startswith("candidate"):
        proposal = excerpt_text(phrase, limit=60)
    else:
        proposal = _LABELS.get(section_id, "Draft term")
    existing = {normalize_text(item.get("label", "")) for item in text_entries.values()}
    if normalize_text(proposal) not in existing:
        return proposal
    index = 2
    while normalize_text(f"{proposal} {index}") in existing:
        index += 1
    return f"{proposal} {index}"


def _aliases(phrase: str) -> list[str]:
    alias = excerpt_text(str(phrase or "").strip(), limit=48)
    return [alias] if " " in alias and alias else []


def _markers(*texts: str) -> list[str]:
    return [phrase.casefold() for phrase in keyword_phrases(*texts) if " " not in phrase and len(phrase) > 2]


def _merge_unique(existing: list[str], additions: list[str]) -> list[str]:
    values = list(existing)
    for item in additions:
        if item not in values:
            values.append(item)
    return values
