from __future__ import annotations

from enum import Enum


class KernelStrEnum(str, Enum):
    @classmethod
    def values(cls) -> tuple[str, ...]:
        return tuple(member.value for member in cls)


_ENUM_ROWS: dict[str, tuple[tuple[str, str], ...]] = {
    "DatabaseEmptiness": (("EMPTY", "empty"), ("FILLED", "filled"), ("UNKNOWN", "unknown")),
    "SemanticReleaseState": (
        ("NO_SEMANTIC_RELEASE", "no_semantic_release"),
        ("SEMANTIC_RELEASE_INCOMPLETE", "semantic_release_incomplete"),
        ("SEMANTIC_RELEASE_COMPLETE_NOT_ACTIVE", "semantic_release_complete_not_active"),
        ("SEMANTIC_RELEASE_ACTIVE", "semantic_release_active"),
        ("UNKNOWN", "unknown"),
    ),
    "AttachPointerOwner": (("KERNEL_HELD", "kernel_held"), ("PIPELINE_HELD", "pipeline_held")),
    "LockType": (
        ("ACTIVE_RUN", "active_run"),
        ("WORKSPACE", "workspace"),
        ("DATABASE", "database"),
        ("RELEASE_ATTACH_ACTIVATION", "release_attach_activation"),
        ("MERGE", "merge"),
        ("REBUILD_OVERWRITE", "rebuild_overwrite"),
    ),
    "LockStatus": (("ACTIVE", "active"), ("RELEASED", "released"), ("FAILED", "failed"), ("PENDING_RESUME", "pending_resume"), ("EXPIRED", "expired")),
    "UserDecision": (("CONFIRMED", "confirmed"), ("REJECTED", "rejected"), ("CANCELLED", "cancelled"), ("EXPIRED", "expired")),
    "InteractionKind": (("INPUT", "input"), ("SELECTION", "selection"), ("CONFIRMATION", "confirmation"), ("NOTICE", "notice"), ("RECOVERY", "recovery")),
    "DialogType": (
        ("FOLDER_PICKER", "folder_picker"),
        ("FOLDER_CREATE_PICKER", "folder_create_picker"),
        ("TEXT_INPUT", "text_input"),
        ("DATABASE_PATH_PICKER", "database_path_picker"),
        ("ACTIVE_DATABASE_CHOICE", "active_database_choice"),
        ("DATABASE_LIST_PICKER", "database_list_picker"),
        ("INPUT_PRESENCE_CONFIRMATION", "input_presence_confirmation"),
        ("UPDATE_MODE_CHOICE", "update_mode_choice"),
        ("GENERIC_CONFIRMATION", "generic_confirmation"),
        ("BLOCKER_NOTICE", "blocker_notice"),
        ("PROGRESS_NOTICE", "progress_notice"),
        ("RECOVERY_DIALOG", "recovery_dialog"),
        ("SUPPORT_BUNDLE_NOTICE", "support_bundle_notice"),
    ),
    "RecoveryDialogType": (
        ("PATH_RESELECTION_DIALOG", "path_reselection_dialog"),
        ("MISSING_INPUT_DIALOG", "missing_input_dialog"),
        ("OVERWRITE_DECISION_DIALOG", "overwrite_decision_dialog"),
        ("MERGE_RECONCILIATION_DIALOG", "merge_reconciliation_dialog"),
        ("STALE_LOCK_DIALOG", "stale_lock_dialog"),
        ("REBIND_DATABASE_ARTIFACT_TREE_DIALOG", "rebind_database_artifact_tree_dialog"),
        ("DISCARD_OR_ARCHIVE_STAGED_WORK_DIALOG", "discard_or_archive_staged_work_dialog"),
        ("PARTIAL_PIPELINE_RUN_RECOVERY_DIALOG", "partial_pipeline_run_recovery_dialog"),
        ("SUPPORT_BUNDLE_DIALOG", "support_bundle_dialog"),
    ),
    "InteractionResponseStatus": (("SUBMITTED", "submitted"), ("CANCELLED", "cancelled"), ("CLOSED", "closed"), ("EXPIRED", "expired"), ("SUPERSEDED", "superseded"), ("REJECTED_STALE", "rejected_stale")),
    "ClientFrontendEventKind": (("INTERACTION_REQUEST", "interaction_request"), ("PROGRESS_EVENT", "progress_event"), ("MIRROR_EVENT", "mirror_event"), ("TOOL_AVAILABILITY", "tool_availability"), ("INTERACTION_RESOLVED", "interaction_resolved")),
    "RiskClass": (("READ_ONLY", "read_only"), ("NON_DESTRUCTIVE", "non_destructive"), ("LONG_RUNNING", "long_running"), ("DESTRUCTIVE", "destructive"), ("SUPPORT", "support")),
    "ProgressStatus": (
        ("STEP_STARTED", "step_started"),
        ("STEP_COMPLETED", "step_completed"),
        ("WAITING_FOR_USER", "waiting_for_user"),
        ("BLOCKED", "blocked"),
        ("RETRYING", "retrying"),
        ("CANCELLED", "cancelled"),
        ("COMPLETED", "completed"),
        ("FAILED", "failed"),
    ),
    "ProgressEventType": (("WORKFLOW_STEP", "workflow_step"), ("PIPELINE_STEP", "pipeline_step"), ("LLM_STEP", "llm_step"), ("USER_INTERACTION", "user_interaction"), ("RECOVERY_STEP", "recovery_step")),
    "MirrorSource": (("KERNEL", "kernel"),),
    "MirrorEventType": (
        ("PROGRESS", "progress"),
        ("INPUT_DIALOG_OPENED", "input_dialog_opened"),
        ("SELECTION_DIALOG_OPENED", "selection_dialog_opened"),
        ("CONFIRMATION_DIALOG_OPENED", "confirmation_dialog_opened"),
        ("BLOCKER", "blocker"),
        ("RECOVERY_STATE", "recovery_state"),
        ("VALIDATION_ERROR", "validation_error"),
        ("PIPELINE_ERROR", "pipeline_error"),
        ("LLM_VALIDATION_RETRY", "llm_validation_retry"),
        ("LLM_VALIDATION_FAILED_FINAL", "llm_validation_failed_final"),
        ("WORKFLOW_COMPLETED", "workflow_completed"),
        ("WORKFLOW_CANCELLED", "workflow_cancelled"),
    ),
    "MirrorSeverity": (("INFO", "info"), ("WARNING", "warning"), ("RECOVERABLE_ERROR", "recoverable_error"), ("FINAL_ERROR", "final_error")),
    "RecoveryOwner": (("KERNEL_DIALOG", "kernel_dialog"), ("AGENT_TOOL", "agent_tool"), ("USER_FILESYSTEM_ACTION", "user_filesystem_action"), ("KERNEL_INTERNAL", "kernel_internal"), ("SUPPORT_SURFACE", "support_surface")),
    "RecoveryActionType": (
        ("REOPEN_DIALOG", "reopen_dialog"),
        ("APPLY_KERNEL_OPTION", "apply_kernel_option"),
        ("RETRY_SAME_WORKFLOW", "retry_same_workflow"),
        ("INSPECT_RESUME_STATE", "inspect_resume_state"),
        ("CANCEL_ACTIVE_WORKFLOW", "cancel_active_workflow"),
        ("START_NEW_WORKFLOW", "start_new_workflow"),
        ("DISCARD_OR_ARCHIVE_STAGED_WORK", "discard_or_archive_staged_work"),
        ("OPEN_SUPPORT_BUNDLE", "open_support_bundle"),
        ("SUPPORT_ONLY", "support_only"),
        ("USER_FILESYSTEM_FIX", "user_filesystem_fix"),
    ),
    "RecoveryStateClass": (
        ("STALE_LOCK", "stale_lock"),
        ("TARGET_IDENTITY_CHANGED", "target_identity_changed"),
        ("BROKEN_DATABASE_ARTIFACT_BINDING", "broken_database_artifact_binding"),
        ("SEMANTIC_RELEASE_INCOMPLETE_STAGED", "semantic_release_incomplete_staged"),
        ("PARTIAL_PIPELINE_RUN", "partial_pipeline_run"),
        ("UNRESOLVED_MERGE_COLLISION", "unresolved_merge_collision"),
        ("MISSING_MANIFEST_OR_ORIGINALS", "missing_manifest_or_originals"),
        ("FINAL_LLM_VALIDATION_FAILURE", "final_llm_validation_failure"),
        ("EXPIRED_PENDING_INTERACTION", "expired_pending_interaction"),
        ("SUPPORT_ONLY_UNRECOVERABLE", "support_only_unrecoverable"),
    ),
    "RecoveryResultStatus": (("APPLIED", "applied"), ("REJECTED", "rejected"), ("STALE", "stale"), ("CANCELLED", "cancelled"), ("SUPPORT_ONLY", "support_only"), ("FAILED", "failed")),
    "AnalysisScope": (("SAMPLE_SET", "sample_set"),),
    "TaxonomySource": (("ACTIVE", "active"), ("STAGED", "staged"), ("CUSTOM_TAXONOMY_UPDATE_STATE", "custom_taxonomy_update_state")),
    "TaxonomyViewMode": (("COMPLETE", "complete"), ("RELEVANT_SLICE", "relevant_slice")),
    "DatabaseCoverageQuality": (("GOOD", "good"), ("MIXED", "mixed"), ("WEAK", "weak")),
    "SampleStructureShape": (("TEXT", "text"), ("FORM", "form"), ("TABLE", "table"), ("FORM_WITH_TABLE", "form_with_table"), ("LIST", "list"), ("MIXED", "mixed")),
    "ValueType": (("STRING", "string"), ("DATE_OR_STRING", "date_or_string"), ("NUMBER_OR_STRING", "number_or_string"), ("NUMBER_OR_MONEY_STRING", "number_or_money_string")),
    "ProposalStatus": (("DRAFT", "draft"), ("ACTIVE", "active"), ("DEPRECATED", "deprecated")),
    "LLMParseStatus": (("VALID_JSON", "valid_json"), ("INVALID_JSON", "invalid_json"), ("MISSING_OUTPUT", "missing_output"), ("NOT_JSON_OBJECT", "not_json_object"), ("NOT_JSON_ARRAY", "not_json_array")),
    "LLMValidationStatus": (("PASSED", "passed"), ("FAILED", "failed"), ("NOT_RUN", "not_run")),
    "LLMResponseStatus": (("COMPLETE", "complete"), ("INCOMPLETE", "incomplete"), ("ERROR", "error")),
    "LLMValidationFailureCode": (
        ("INVALID_JSON", "invalid_json"),
        ("MARKDOWN_OUTSIDE_JSON", "markdown_outside_json"),
        ("SCHEMA_VERSION_MISMATCH", "schema_version_mismatch"),
        ("MISSING_REQUIRED_FIELDS", "missing_required_fields"),
        ("UNKNOWN_FIELDS", "unknown_fields"),
        ("ENUM_MISMATCH", "enum_mismatch"),
        ("SOURCE_FINGERPRINT_MISMATCH", "source_fingerprint_mismatch"),
        ("TAXONOMY_FINGERPRINT_MISMATCH", "taxonomy_fingerprint_mismatch"),
        ("PROJECTION_FINGERPRINT_MISMATCH", "projection_fingerprint_mismatch"),
        ("SAMPLE_ID_MISMATCH", "sample_id_mismatch"),
        ("DATABASE_REFERENCE_MISMATCH", "database_reference_mismatch"),
        ("UNKNOWN_TAXONOMY_CODE", "unknown_taxonomy_code"),
        ("UNKNOWN_PROJECTION_ID", "unknown_projection_id"),
        ("INVALID_UPDATE_STATE_FAMILY", "invalid_update_state_family"),
        ("INVALID_PROMOTION_PATH", "invalid_promotion_path"),
        ("FUNCTION_RULE_VIOLATION", "function_rule_violation"),
    ),
    "TaxonomySampleHintType": (("POSSIBLE_MATCH", "possible_match"), ("POSSIBLE_GAP", "possible_gap"), ("POSSIBLE_MISFIT", "possible_misfit")),
    "TaxonomyDatabaseGapSource": (("TAXONOMY_GAP_SEED", "taxonomy_gap_seed"), ("ISSUE_CLUSTER", "issue_cluster"), ("COVERAGE_METRIC", "coverage_metric"), ("AFFECTED_DOCUMENT", "affected_document")),
    "TaxonomyDatabaseHintType": (("POSSIBLE_GAP", "possible_gap"), ("POSSIBLE_EXTENSION", "possible_extension")),
    "ProjectionSampleHintType": (("POSSIBLE_MATCH", "possible_match"), ("POSSIBLE_GAP", "possible_gap"), ("POSSIBLE_MISFIT", "possible_misfit")),
    "ProjectionDatabaseGapSource": (("PROJECTION_GAP_SEED", "projection_gap_seed"), ("ISSUE_CLUSTER", "issue_cluster"), ("COVERAGE_METRIC", "coverage_metric"), ("SLOT_COVERAGE", "slot_coverage"), ("AFFECTED_DOCUMENT", "affected_document")),
    "ProjectionDatabaseHintType": (("POSSIBLE_PROJECTION_EXTENSION", "possible_projection_extension"), ("POSSIBLE_NEW_PROJECTION", "possible_new_projection"), ("POSSIBLE_PROMOTION_RULE", "possible_promotion_rule")),
    "MergeRoute": (("EMPTY_DATABASES_MERGE_PATH", "empty_databases_merge_path"), ("FILLED_DATABASES_MERGE_PATH", "filled_databases_merge_path")),
    "ProjectionMergeMode": (("PRESERVE_SOURCE_PROJECTIONS", "preserve_source_projections"), ("MERGE_TO_SINGLE_PROJECTION", "merge_to_single_projection")),
    "MergeCollisionResolutionStatus": (("UNRESOLVED", "unresolved"), ("RESOLVED", "resolved"), ("REQUIRES_USER_CHOICE", "requires_user_choice"), ("SUPPORT_ONLY", "support_only")),
    "PipelineBatchKind": (("MANUAL_INGEST", "manual_ingest"), ("SAMPLE_INGEST", "sample_ingest"), ("REINGEST_ALL_ORIGINALS", "reingest_all_originals"), ("REINGEST_SELECTED_SAMPLES", "reingest_selected_samples"), ("WORKFLOW_CONTINUATION_INGEST", "workflow_continuation_ingest")),
    "PipelineBatchStatus": (("FINALIZED", "finalized"),),
}


def _enum(name: str, rows: tuple[tuple[str, str], ...]) -> type[KernelStrEnum]:
    return KernelStrEnum(name, dict(rows), module=__name__)


globals().update({name: _enum(name, rows) for name, rows in _ENUM_ROWS.items()})
__all__ = ["KernelStrEnum", *_ENUM_ROWS]
