from __future__ import annotations


def runtime_required_files(package_name: str) -> list[str]:
    return [
        "runtime/python/python.exe",
        "runtime/python/pythonw.exe",
        "runtime/python/python3.dll",
        "runtime/python/python311.dll",
        "runtime/python/vcruntime140.dll",
        "runtime/python/vcruntime140_1.dll",
        "runtime/python/Lib/encodings/__init__.py",
        "runtime/python/Lib/site-packages/requests/__init__.py",
        "runtime/python/Lib/site-packages/yaml/__init__.py",
        "runtime/requirements.lock.txt",
        "vision_pipeline_shared/__init__.py",
        "vision_pipeline_shared/semantic_identity.py",
        f"{package_name}/__main__.py",
        f"{package_name}/projection_routing_settings.py",
        f"{package_name}/shared_identity.py",
        f"{package_name}/edit_contract/__init__.py",
        f"{package_name}/edit_contract/__main__.py",
        f"{package_name}/edit_contract/describe_surfaces.py",
        f"{package_name}/edit_contract/read_surface.py",
        f"{package_name}/edit_contract/repository.py",
        f"{package_name}/edit_contract/summary.py",
        f"{package_name}/edit_contract/types.py",
        f"{package_name}/edit_contract/validate_surface.py",
        f"{package_name}/edit_contract/validation.py",
        f"{package_name}/edit_contract/workflow.py",
        f"{package_name}/edit_contract/write_surface.py",
        f"{package_name}/main/__init__.py",
        f"{package_name}/normalizer/batch_limits.py",
        f"{package_name}/normalizer/batch_parallel.py",
        f"{package_name}/orchestrator_contract/__init__.py",
        f"{package_name}/orchestrator_contract/adapter.py",
        f"{package_name}/orchestrator_contract/__main__.py",
        f"{package_name}/orchestrator_contract/debug_support.py",
        f"{package_name}/orchestrator_contract/debug_workflow.py",
        f"{package_name}/orchestrator_contract/types.py",
        f"{package_name}/orchestrator_contract/value_parsing.py",
        f"{package_name}/orchestrator_contract/validation.py",
        f"{package_name}/orchestrator_contract/workflow.py",
        f"{package_name}/semantic_release/shared_identity.py",
        f"{package_name}/source_authoring/minimal_custom_release.py",
        "module-manifest.json",
        "config/config.yaml",
        "config/prompt_bundle.json",
        "config/prompt_overrides.json",
        "config/semantic_release.recipe.json",
        "check-runtime.bat",
        "tools/check-runtime.ps1",
    ]
