"""Path-stable validation surface for Edit-Suite-facing contract commands."""

from __future__ import annotations

from .validation_keys import (
    _BACKFILL_STALE_KEYS,
    _BASIC_RELATION_MINING_KEYS,
    _CREATE_AND_REBUILD_NEW_CORPUS_DB_KEYS,
    _DATABASE_ANALYSIS_KEYS,
    _EXPORT_KEYS,
    _LOAD_SEMANTIC_RELEASE_KEYS,
    _MERGE_CORPUS_DATABASES_KEYS,
    _MERGE_PHASE19_KEYS,
    _MERGE_PREFLIGHT_KEYS,
    _PIPELINE_BATCH_KEYS,
    _PREVIEW_REBUILD_KEYS,
    _READ_ACTIVE_SEMANTIC_RELEASE_KEYS,
    _REBUILD_KEYS,
    _RESET_ACTIVE_CORPUS_DB_KEYS,
    _SEARCH_KEYS,
    _SEMANTIC_AUDIT_KEYS,
    _SEMANTIC_STATUS_KEYS,
    _STATS_KEYS,
    _VALIDATE_ARTIFACT_TREE_KEYS,
)
from .validation_owner_commands import (
    parse_backfill_sql_from_merge_artifacts_command,
    parse_cleanup_pipeline_batch_materialization_command,
    parse_extract_sample_files_for_reingest_command,
    parse_inspect_latest_pipeline_batch_command,
    parse_multi_source_merge_databases_command,
    parse_multi_source_merge_preflight_command,
    parse_read_database_analysis_evidence_command,
    parse_reingest_pipeline_batch_command,
    parse_restore_pipeline_batch_originals_command,
    parse_validate_artifact_tree_command,
    parse_write_merge_reconciliation_manifest_command,
)
from .validation_owner_envelope import _request_fingerprint, _require_phase19_owner_envelope
from .validation_standard_commands import (
    _artifact_args,
    _missing,
    _optional_text,
    parse_backfill_stale_command,
    parse_basic_relation_mining_command,
    parse_create_and_rebuild_new_corpus_db_command,
    parse_export_command,
    parse_load_semantic_release_command,
    parse_merge_corpus_databases_command,
    parse_merge_preflight_command,
    parse_preview_rebuild_from_artifacts_command,
    parse_read_active_semantic_release_command,
    parse_rebuild_from_artifacts_command,
    parse_reset_active_corpus_db_command,
    parse_search_command,
    parse_semantic_audit_command,
    parse_semantic_status_command,
    parse_stats_command,
)

__all__ = [
    "parse_backfill_stale_command",
    "parse_backfill_sql_from_merge_artifacts_command",
    "parse_basic_relation_mining_command",
    "parse_cleanup_pipeline_batch_materialization_command",
    "parse_create_and_rebuild_new_corpus_db_command",
    "parse_extract_sample_files_for_reingest_command",
    "parse_export_command",
    "parse_inspect_latest_pipeline_batch_command",
    "parse_load_semantic_release_command",
    "parse_merge_corpus_databases_command",
    "parse_merge_preflight_command",
    "parse_multi_source_merge_databases_command",
    "parse_multi_source_merge_preflight_command",
    "parse_preview_rebuild_from_artifacts_command",
    "parse_read_active_semantic_release_command",
    "parse_read_database_analysis_evidence_command",
    "parse_reingest_pipeline_batch_command",
    "parse_rebuild_from_artifacts_command",
    "parse_reset_active_corpus_db_command",
    "parse_restore_pipeline_batch_originals_command",
    "parse_search_command",
    "parse_semantic_audit_command",
    "parse_semantic_status_command",
    "parse_stats_command",
    "parse_validate_artifact_tree_command",
    "parse_write_merge_reconciliation_manifest_command",
]
